In [1]:
%matplotlib inline

In [3]:
import torch
import numpy as np

Tensors can be initialized in various ways. Take a look at the following example :
** Directly from the data **

Tensors can be created directly from the data. The data type is automatically inferred

In [4]:
data = [[1, 2], [3, 4], [5, 6], [7, 8]]
x_data = torch.tensor(data)

For Numpy array:

Tensors can be created from the numpy arrays and vice versa.

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unlless ecxplicity overridden

In [6]:
"""Retain the properties of x_data"""
x_ones = torch.ones_like(x_data)  
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float)   # overrides the datatype of x_data.
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0286, 0.9037],
        [0.1327, 0.5345],
        [0.7517, 0.7327],
        [0.8604, 0.0849]]) 



With random or constant values:

Shape is a tuple of tensor dimensions. in the functions below, it determines the dimensionally of the output tensor.


In [7]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.4539, 0.3120, 0.5034],
        [0.5847, 0.2809, 0.0288]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



Tensor Attributes :

Tensor attributes describe their shape, datatype and the device on which they are stored

In [9]:
tensor = torch.rand(3, 4)
print(f"Shape of Tensor: \n {tensor.shape} \n")
print(f"Datatype of tensor: \n {tensor.dtype} \n")
print(f"Device tensor is stored on: \n {tensor.device} \n")

Shape of Tensor: 
 torch.Size([3, 4]) 

Datatype of tensor: 
 torch.float32 

Device tensor is stored on: 
 cpu 



Tensor Operations:


Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are comprehensively described
here --> https://pytorch.org/docs/stable/torch.html

Each of them can be run on the GPU ( at typically higher speeds than on a CPU).

In [10]:
"""We Move our tensor to the GPU if available"""

if torch.cuda.is_available():
    tensor = tensor.to(cuda)
    print(f"Device tensor is stored on the : {tensor.device}")

Standard Numpy-like indexing and slicing 


In [11]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining tensors: You can use torch.cat to concatenate a sequence of tensors along a given dimension. see also torch.stack

https://pytorch.org/docs/stable/generated/torch.stack.html   another tensor joining op that is subtly different from torch.car

In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Multiplying tensors

In [13]:
#this computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
#alternate syntax
print(f"tensor * tensor \n {tensor @ tensor.T}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


This computes matrix multiplication between two tensors

In [14]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
#alternate syntax
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In-place operations:

Operations that a _ suffix are in-place. For e.g. x.copy_(y), x.t_().will change x.

In [15]:
print (tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**Note**

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence,
their use is discouraged

***Bridge With Numpy***

Tensors on the CPU and Numpy arrays can share their underlying memory
locations, and changing one will change the other.

*** Tensor to Numpy array ***

In [16]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the numoy array

In [17]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Numpy array to Tensor

In [18]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the numpy array reflect in the tensor

In [19]:
np.add(n, 1, out =n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
